const LABELS_TO_ADD = [
  { name: 'Priority: Highest', color: 'b60205', priority: 1 },
  { name: 'Priority: High', color: 'fef2c0', priority: 2 },
  { name: 'Priority: Medium', color: 'd4c5f9', priority: 3 },
  { name: 'Priority: Low', color: 'd4c5f9', priority: 4 },
  { name: 'Priority: Lowest', color: 'ededed', priority: 5 },
  { name: 'Category: Backend', color: 'c2e0c6', priority: null },
  { name: 'Category: Business/Meetings', color: '0e8a16', priority: null },
  { name: 'Category: DevOps', color: 'fef2c0', priority: null },
  { name: 'Category: Frontend', color: 'bfdadc', priority: null },
  { name: 'Category: Infrastructure', color: 'f0e68c', priority: null },
  { name: 'Category: Report', color: '40e0d0', priority: null },
  { name: 'Category: Unit test', color: 'ededed', priority: null },
  { name: 'Level: Easy', color: '48d1cc', priority: null },
  { name: 'Level: Medium', color: '20b2aa', priority: null },
  { name: 'Level: Hard', color: '008b8b', priority: null },
  { name: 'Stage: Analysis', color: 'e6e6e6', priority: null },
  { name: 'Stage: Backlog', color: 'ededed', priority: null },
  { name: 'Stage: Cancelled', color: '000000', priority: null },
  { name: 'Stage: In progress', color: 'fbca04', priority: null },
  { name: 'Stage: Review', color: '0052cc', priority: null },
  { name: 'Stage: Testing', color: 'e616e6', priority: null },
  { name: 'Status: Blocked', color: 'd93f0b', priority: null },
  { name: 'Status: Duplicated', color: 'c5def5', priority: null },
  { name: 'Status: Impediment', color: 'b60205', priority: null },
  { name: 'Status: Needs Fixing', color: 'ff8c00', priority: null },
  { name: 'Type: Bug', color: 'fc2929', priority: null },
  { name: 'Type: Improvement', color: '84b6eb', priority: null },
  { name: 'Type: New feature', color: '0052cc', priority: null },
  { name: 'Type: Sub-task', color: 'ededed', priority: null },
];

export default LABELS_TO_ADD;